name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y python3 make g++
    
    - name: Install dependencies
      run: |
        # Clear pnpm store to ensure fresh builds
        pnpm store prune
        pnpm install --frozen-lockfile --force
        
    - name: Rebuild better-sqlite3
      run: |
        cd node_modules/.pnpm/better-sqlite3@12.0.0/node_modules/better-sqlite3
        npm rebuild
    
    - name: Run type checking
      run: pnpm run lint
    
    - name: Run tests
      run: pnpm test
    
    - name: Build project
      run: pnpm run build